### PR TITLE
Bug fixes

### LINKED ISSUE #1: M/K v M and K
When entering value of M/K in the LBI tool - this works fine. When entering separately M and K - this gives a non-fatal error :
image
image

The results display correctly, but the report does not download (though the zip file does).

### PR DESCRIPTION
**Pull request by tokami**
Fixes #1, #2, #3

Successful integration with WPS will depend on R package lbmsmt to be updated on the i-marine platform. Main branch of  https://github.com/tokami/lbmsmt updated on 11/05 19:10.

### CODE REVIEW

**Comment by tokami** [comment]
Do we need to write a ticket for lbmsmt to be updated on the platform?

**Review by eblondel — CHANGES_REQUESTED** [review]
I don't think we should add this specific rule but instead rename the repo in package.json from `AnalytixWare/ShinySky` to `AnalytixWare/shinysky` (repo names are case insensitive)
In this way the package utils will work and `shinysky` will be loaded

**Review by eblondel — APPROVED** [review]

**Review by eblondel — APPROVED** [review]

**Review by eblondel — APPROVED** [review]

**Review by eblondel — APPROVED** [review]

**Comment by eblondel** [comment]
> Do we need to write a ticket for lbmsmt to be updated on the platform?

Better write a ticket to ask for its update (or to check whether it is updated as nightly build)

**Comment by eblondel** [comment]
@tokami if you can address the shinysky issue (renaming the repo in package.json) and remove the specific rule you added in package utils.

**Comment by eblondel** [comment]
Hi @tokami can you address the above the change so I can merge it?

**Comment by tokami** [comment]
I fixed the shinysky issue

**Review by eblondel — APPROVED** [review]

**Pull request merged**
